#!/bin/bash

set -e

while [ $# -gt 0 ]; do
    case $1 in
        --build)
            ci/check_build.py
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done
